In [4]:
#NumPy aka Numerical Python is a library that provids support fot workig with arrays and matrices, widely used in data analysis, ml
import numpy as np
print("NumPy Imported Successfully! ✅")

NumPy Imported Successfully! ✅


In [10]:
#create 1d array
arr= np.array([1,2,3,4,5,6])
print(arr)
# Check type
print(type(arr))
# check datatype of the elem
print(arr.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32


In [17]:
#create 2d array
arr_2d= np.array([
    [1,2,3,4], 
    [5,6,7,8]
])

print(arr_2d)

#check dimention
print(arr_2d.ndim)

#basic operations(elment wise operations)
a= np.array([1,2,3])
b= np.array([4,5,6])

print("the addition of the elements of a and b is: ", a+b)
print("the subtracttion of the elements of a from b is: ", a-b)
print("the multiplication of the elements of a and b is: ", a*b)
print("the division of eleemnts of a wrt to b is: ", a/b)

#scalar operations
c= np.array([3,2,1])

print("adding +2 to all the elemets of c: ", c+2)
print("multiplying 3 to all the elements of c: ", c*3)

[[1 2 3 4]
 [5 6 7 8]]
2
the addition of the elements of a and b is:  [5 7 9]
the subtracttion of the elements of a from b is:  [-3 -3 -3]
the multiplication of the elements of a and b is:  [ 4 10 18]
the division of eleemnts of a wrt to b is:  [0.25 0.4  0.5 ]
adding +2 to all the elemets of c:  [5 4 3]
multiplying 3 to all the elements of c:  [9 6 3]


In [24]:
#create 3d array (stacking of 2d arrays)
arr_3d= np.array([
    [
        [1,2,3,4], 
        [5,6,7,8], 
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])
print(arr_3d)

#dimentiion
print("the dimention of the array is: ", arr_3d.ndim)

#shape
print("the shap of the array is: ", arr_3d.shape) # 2 depth, 3 rows, 4 coloumns

#acessing the elements of 3d arrays
print("the array present at 1st depth: \n", arr_3d[0])

print("the second row of the first depth array: \n", arr_3d[0,1])

print("acessing a specific element present at 2nd depth array, 3rd row, 4th coloumn: ", arr_3d[1,2,3])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
the dimention of the array is:  3
the shap of the array is:  (2, 3, 4)
the array present at 1st depth: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
the second row of the first depth array: 
 [5 6 7 8]
acessing a specific element present at 2nd depth array, 3rd row, 4th coloumn:  24


In [14]:
import numpy as np

# Create a 4D array with shape (2, 2, 3, 4)
tensor = np.array([
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],  # 3x4 matrix
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]  # 3x4 matrix
    ],
    [
        [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]],  # 3x4 matrix
        [[37, 38, 39, 40], [41, 42, 43, 44], [45, 46, 47, 48]]  # 3x4 matrix
    ]
])

print(tensor)
print("Shape:", tensor.shape)  # (2, 2, 3, 4)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]
Shape: (2, 2, 3, 4)


In [6]:
#assignement create 4x4 matrix and find its shape
fourbyfour= np.array([
     [1,2,3,4], 
     [5,6,7,8],
     [9,10,11,12], 
     [13,14,15,16]
])

print(fourbyfour)
print(fourbyfour.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [3]:
arr= np.array([1,2,3,4])

print( arr + 5) # adds + 5 to each elements
print( arr * 2) # multiply 2 to each elements
print( arr / 10) # divides 10 from each elment
print( arr ** 2) # sqaure each elemnts

[6 7 8 9]
[2 4 6 8]
[0.1 0.2 0.3 0.4]
[ 1  4  9 16]


In [30]:
a= np.array([
    [1,2], [3,4]
])

b= np.array([
    [5,6], [7,8]
])

print(a + b) #matrix addition
print(a * b) #element wise multiplication
print(np.dot(a, b)) #mateix multiplication

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [11]:
#assignment create 5x5 matrix with random values and find its mean and sum.
fivebyfive= np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])

print(fivebyfive)
print("the sum of the above 5x5 matrix is ", np.sum(fivebyfive)) 
print("the mean of the abve 5x5 matrix is", np.mean(fivebyfive))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
the sum of the above 5x5 matrix is  325
the mean of the abve 5x5 matrix is 13.0


In [12]:
#assignment generate randome values for a 5x5 matrix and fine mean and sum of that matrix.
matrix = np.random.randint(1, 101, (5,5))  # Random numbers between 1-100
print(matrix)

print("Sum:", np.sum(matrix))
print("Mean:", np.mean(matrix))


[[79 27 19 13 99]
 [86 42 18 10 94]
 [78 42 91 18 68]
 [86 31 42 89 53]
 [27 83 71 57 28]]
Sum: 1351
Mean: 54.04


In [13]:
print( np.zeros((3,3))) #3x3 matrix of zeros
print(np.ones((2,2))) #2x2 matrix of ones
print(np.eye((4))) #4x4 identity matrix

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
print(np.random.rand(3,3)) #random numbers between 0 & 1 in 3x3 matrix
print(np.random.randint(10, 50, (3,3))) #random integer from 10 to 50 in 3x3 matrix

[[0.62554741 0.27364167 0.15762278]
 [0.45658695 0.78656051 0.07892692]
 [0.31484431 0.51150276 0.22410258]]
[[17 16 16]
 [39 36 14]
 [21 19 32]]


In [19]:
arr= np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.reshape(3,2)) # change shape
print(arr.T) #transpose the matrix

[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [22]:
#assignment create 6x6 random matrix, find its transpose and calculatr its mean
sixbysix= np.random.randint(0, 50, (6,6))
print(sixbysix)
print(sixbysix.shape)
print("the transpose of the above 6x6 is: ", sixbysix.T)
print("the mean of the above 6x6 matrix is: ", np.mean(sixbysix))

[[39 46  1 23 17 37]
 [48 13 48 49 31 22]
 [24  4 34 34 30 42]
 [ 5 35 37 19  6 49]
 [ 8 18 25 28 15 20]
 [12 22  6  8  6 38]]
(6, 6)
the transpose of the above 6x6 is:  [[39 48 24  5  8 12]
 [46 13  4 35 18 22]
 [ 1 48 34 37 25  6]
 [23 49 34 19 28  8]
 [17 31 30  6 15  6]
 [37 22 42 49 20 38]]
the mean of the above 6x6 matrix is:  24.97222222222222


In [5]:
#assignment normalizeing matrix by scaling the values between 0 and 1 using min-max normalization
matrix= np.random.randint(1,101,(6,6)) 
normalized_matrix= (matrix - matrix.min())/(matrix.max() - matrix.min())

print("original matrix:\n", matrix)
print("the min value in the matrix is:", matrix.min())
print("the max value in the matrix is :", matrix.max())
print("normalized matrix:\n", normalized_matrix)

original matrix:
 [[88 95  6 39 46  1]
 [ 1 63 78 49 96 56]
 [45 37 53 57 61 50]
 [22 71 97 14 48 17]
 [53 62 18 23 55 57]
 [16 75 70 34 80 29]]
the min value in the matrix is: 1
the max value in the matrix is : 97
normalized matrix:
 [[0.90625    0.97916667 0.05208333 0.39583333 0.46875    0.        ]
 [0.         0.64583333 0.80208333 0.5        0.98958333 0.57291667]
 [0.45833333 0.375      0.54166667 0.58333333 0.625      0.51041667]
 [0.21875    0.72916667 1.         0.13541667 0.48958333 0.16666667]
 [0.54166667 0.63541667 0.17708333 0.22916667 0.5625     0.58333333]
 [0.15625    0.77083333 0.71875    0.34375    0.82291667 0.29166667]]


In [25]:
#min-max normalization vs z-score standardization
from sklearn.preprocessing import StandardScaler

# Your original matrix
matrix = np.array([
    [49, 60, 11, 51, 10, 16],
    [44, 75, 98, 36, 24, 56],
    [31, 40, 40, 66, 74, 86],
    [89, 97, 70, 47, 5, 63],
    [91, 10, 67, 19, 13, 81],
    [39, 29, 89, 32, 55, 53]
])

# Apply Z-score Standardization
scaler = StandardScaler()
standardized_matrix = scaler.fit_transform(matrix)

#apply max-min normalization
normalized_matrix= (matrix - matrix.min())/(matrix.max() - matrix.min())

print("\nZ-score Standardized Matrix:\n", standardized_matrix)
print("\nMax-Min normalaization Matrix:\n", normalized_matrix)



Z-score Standardized Matrix:
 [[-0.34242299  0.28136303 -1.74978869  0.61182911 -0.78990542 -1.89212462]
 [-0.55206972  0.79815227  1.20616502 -0.3893458  -0.24154133 -0.13880451]
 [-1.09715121 -0.40768929 -0.76447079  1.61300402  1.71690185  1.17618557]
 [ 1.33475084  1.55610983  0.2548236   0.34484913 -0.98574973  0.16802651]
 [ 1.41860953 -1.44126777  0.15289416 -1.52401069 -0.67239882  0.95702056]
 [-0.76171645 -0.78666807  0.9003767  -0.65632577  0.97269344 -0.27030352]]

Max-Min normalaization Matrix:
 [[0.47311828 0.59139785 0.06451613 0.49462366 0.05376344 0.11827957]
 [0.41935484 0.75268817 1.         0.33333333 0.20430108 0.5483871 ]
 [0.27956989 0.37634409 0.37634409 0.65591398 0.74193548 0.87096774]
 [0.90322581 0.98924731 0.69892473 0.4516129  0.         0.62365591]
 [0.92473118 0.05376344 0.66666667 0.15053763 0.08602151 0.8172043 ]
 [0.3655914  0.25806452 0.90322581 0.29032258 0.53763441 0.51612903]]


In [8]:
arr= np.array(
    [10,20,30,40] #1d array
)

print(arr[0]) #First element
print(arr[-1]) #last element
print(arr[1:4])  # Slice the array

10
40
[20 30 40]


In [34]:
matrix= np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix)
print(matrix[0, 1]) #row0, column 1
print(matrix[:,1]) #all row column 1
print(matrix[1,:]) #row1, all colomun

[[1 2 3]
 [4 5 6]]
2
[2 5]
[4 5 6]


In [37]:
#assignment create a 4x4 matrix ans extract the second column
fourbyfour= np.random.randint(0, 50, (4,4))

print("matrix: \n", fourbyfour)
print("the second column in the above matrix is: \n", fourbyfour[:, 1])

matrix: 
 [[47 38 22 20]
 [29 26 42 45]
 [ 7 37  4 40]
 [40  7 12 43]]
the second column in the above matrix is: 
 [38 26 37  7]


In [38]:
#assignment create a 5x5 matrix and extract third row
fivebyfive= np.random.randint(0, 50, (5,5))

print("matrix: \n", fivebyfive)
print("3rd row of the above matrix: \n", fivebyfive[2, :])

matrix: 
 [[36 49 17 44 29]
 [34 24 15 15  3]
 [ 9  7 43 36  5]
 [31 49 30 27 33]
 [21  2 34  4 28]]
3rd row of the above matrix: 
 [ 9  7 43 36  5]


In [41]:
#assignment creatre 4x4 matrix and extract the diagonal elements
fourbyfour= np.random.randint(0,50,(4,4))

print("matrix: \n", fourbyfour)
print("the diagonal elements are \n", np.diag(fourbyfour))
print("the diagonal elements are \n", np.sum(np.diag(fourbyfour)))

matrix: 
 [[45 13 14 12]
 [48 20 47 25]
 [ 9 40 29 12]
 [16 11 22 13]]
the diagonal elements are 
 [45 20 29 13]
the diagonal elements are 
 107


In [44]:
#assignment creatre 5x5 matrix and extract the diagonal elements and find its sum
fivebyfive= np.random.randint(0,50,(5,5))

print("matrix: \n", fivebyfive)
print("the diagonal elements are \n", np.diag(fivebyfive))
print("the sum of diagonal elements are \n", np.sum(np.diag(fivebyfive)))

matrix: 
 [[31 35 40 38 39]
 [13 41 30 27 40]
 [27  3 43 23 24]
 [ 9 39  9  7  2]
 [29 16 41  3 41]]
the diagonal elements are 
 [31 41 43  7 41]
the sum of diagonal elements are 
 163


In [46]:
#assignment create a 6x6 matrix and extract the last coloumn
sixbysix= np.random.randint(0, 50, (6,6))

print("matrix: \n", sixbysix)
print("last coloumn of the above matrix: \n", sixbysix[:, -1])

matrix: 
 [[48 29 43 36 26  2]
 [35 35 20 13  9  1]
 [47  8 40 14 39 10]
 [18  6 14 12 24 10]
 [29 31 15  0  7  0]
 [ 7 15  9 26 33  4]]
last coloumn of the above matrix: 
 [ 2  1 10 10  0  4]


In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Access the element in the first row, second column
print(arr_2d[0, 1])  # 2

# Slice the array
print(arr_2d[:, 1:3])  # [[2 3]
                       #  [5 6]]

2
[[2 3]
 [5 6]]


In [13]:
#broadcasting in numpy
arr= np.random.rand(1,3)
print(arr)
#hres 10 is broadcasted into a matrix like this [10, 10, 10] then added to the matrix in arr var
result= arr+ 10 
print(result)

[[0.62298247 0.00552206 0.07576561]]
[[10.62298247 10.00552206 10.07576561]]


In [16]:
arr_2d= np.array([
    [[1,2,3], 
     [4,5,6]]
])

arr_1d= np.array([10,20,30])
#here the 1d array [10,20,30] is broadcsated in the form [[10,20,30], [10,20,30]] and then added to the 2d array
result= arr_2d + arr_1d
print(result)

[[[11 22 33]
  [14 25 36]]]


In [21]:
arr_3x1= np.array([[1], [2], [3]])
arr_1x4= np.array([10,20,30,40])

result= arr_3x1 + arr_1x4
print("3x1: \n", arr_3x1)
print("1x4: \n", arr_1x4)
print("adding 3x1 + 1x4: \n", result)
# here the 3x1 matrix is broadcasted to [[1,1,1,1], [2,2,2,2], [3,3,3,3]]
#the 1x4 matrix is broadcared to [[10,20,30,40], [10,20,30,40], [10,20,30]]
#atlast the addition is performed to the above two broadcasted mateices and the result in given

3x1: 
 [[1]
 [2]
 [3]]
1x4: 
 [10 20 30 40]
adding 3x1 + 1x4: 
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [25]:
arr_2x3= np.array([
     [1,2,3],
     [4,5,6]
])

arr_1x4= np.array([10,20,30,40])
#accc to the broadcast rule the missmatched matrices which cannot be streached/broadcasted logically will throw a ValueError
#acc to broadcast rule any matrices which are undergoing an opretion must have an equal tailing dimention or 1 as a tailing dimention
try:
    result= arr_2x3 + arr_1x4
except ValueError as err:
    print("Error: ", err)

Error:  operands could not be broadcast together with shapes (2,3) (4,) 


In [28]:
A= np.array([
    [4,7],
    [2,6]
])

A_inv= np.linalg.inv(A)
print("the inverse of the the matrix A is: \n", A_inv)

A_det= np.linalg.det(A)
print("the determenint of A is: \n", A_det)
#vrify if A_inv is the inverse of matrix A using A.A^-1 = A^-1.A= I
identity= np.dot(A, A_inv)
print("A * A_inv: \n", identity)

the inverse of the the matrix A is: 
 [[ 0.6 -0.7]
 [-0.2  0.4]]
the determenint of A is: 
 10.000000000000002
A * A_inv: 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [31]:
#solving linear equations by using formula A.X= B where,
#A is the coefficiet matrix
#X is the variable matrix
#B is the constant matrix
# hence the solution will be X= A^-1.B

A= np.array([
    [4,7],
    [2,6]
])
B= np.array([5,3])

X= np.dot(np.linalg.inv(A), B)
print("the solution matrix X is :\n", X)

the solution matrix X is :
 [0.9 0.2]


In [34]:
#a singular matrix is the matrix which has the determinant to be zero and it cannot be invertible
C= np.array([
    [1,2],
    [2,4]
])

try:
    C_inv= np.linalg.inv(C)
except np.linalg.LinAlgError as err:
    print("Error", err)

Error Singular matrix


In [12]:
#verify using A * v_1 = lambda_1 * v_1
import numpy as np

# Define a 2x2 matrix
A = np.array([[4, 2], [1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Verify the first eigenvalue and eigenvector
lambda_1 = eigenvalues[0]
v_1 = eigenvectors[:, 0]  # Extract the first eigenvector as a 1D array

# Compute A * v_1
Av_1 = np.dot(A, v_1)

# Compute lambda_1 * v_1
lambda_v_1 = lambda_1 * v_1

print("A * v_1:", Av_1)
print("lambda_1 * v_1:", lambda_v_1)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
A * v_1: [4.47213595 2.23606798]
lambda_1 * v_1: [4.47213595 2.23606798]


In [16]:
#assignment compute the eigenvalues and eignevectord of the following matrix [[3,1], [1,3]]
matrix= np.array([
    [3,1],
    [1,3]
])

print("matrix:\n", matrix)

eigenval, eigenvec= np.linalg.eig(matrix)
print("eignevalue:", eigenval)
print("eigenvector: \n", eigenvec)


matrix:
 [[3 1]
 [1 3]]
eignevalue: [4. 2.]
eigenvector: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [17]:
#verify that A.v=lambda.v
v_1= eigenvec[:,0]
lambda_1= eigenval[0]

Av_1= np.dot(matrix, v_1)
lambda_1v_1= lambda_1 * v_1

print("Av_1: \n", Av_1)
print("lambda_1v_1: \n", lambda_1v_1)

Av_1: 
 [2.82842712 2.82842712]
lambda_1v_1: 
 [2.82842712 2.82842712]


In [20]:
#assignment find the inverse of the following matrix [[3,1], [2,4]]
matrix= np.array([
    [3,1],
    [2,4]
])

print("the matrix: \n", matrix)

invmatrix= np.linalg.inv(matrix)
print("inverted matrix: \n", invmatrix)

#verify matrix * invmatrix= I
print(np.dot(matrix, invmatrix))

the matrix: 
 [[3 1]
 [2 4]]
inverted matrix: 
 [[ 0.4 -0.1]
 [-0.2  0.3]]
[[1. 0.]
 [0. 1.]]


In [26]:
#assignment solve for the following linear equatuin: 2x+3y=8, 4x+y=6
#AX= B => X= A^-1B
A= np.array([
    [2,3],
    [4,1]
])

B= np.array([8,6])

X= np.dot(np.linalg.inv(A), B)

print("the solution X: \n", X)
#verify by pluging into the given equation i.e 2(1) + 3(2)= 8 and 4(1) + 2= 6 hence solution matrix is confirmend

the solution X: 
 [1. 2.]


In [ ]:
#assignment normalise a 2d array by subrtacting the me